//
//  WeatherViewController.swift
//  RiaWeather2
//
//  Created George Kyrylenko on 9/1/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherViewController: UIViewController, WeatherViewProtocol {
	var presenter: WeatherPresenterProtocol?
    var weathers = [CityWeather](){
        didSet{
            DispatchQueue.main.async {
                self.weatherTableView.reloadData()
            }
        }
    }
    @IBOutlet weak var weatherTableView: UITableView!
    
	override func viewDidLoad() {
        super.viewDidLoad()
        WeatherRouter.createModule(view: self)
        self.presenter?.getWeather()
    }

    func setWeather(weather: WeatherData) {
        weathers = weather.list ?? []
    }
    @IBAction func AddCityAction(_ sender: Any) {
       let addCityView = AddCityRouter.createModule()
        addCityView.delegate = self
        self.navigationController?.pushViewController(addCityView, animated: true)
    }
}
