//
//  AddCityRouter.swift
//  RiaWeather2
//
//  Created George Kyrylenko on 9/3/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AddCityRouter: AddCityWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> AddCityViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = AddCityViewController(nibName: nil, bundle: nil)
        let interactor = AddCityInteractor()
        let router = AddCityRouter()
        let presenter = AddCityPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
