//
//  AddCityProtocols.swift
//  RiaWeather2
//
//  Created George Kyrylenko on 9/3/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol AddCityWireframeProtocol: class {

}
//MARK: Presenter -
protocol AddCityPresenterProtocol: class {
    func getCities()
}

//MARK: Interactor -
protocol AddCityInteractorProtocol: class {

  var presenter: AddCityPresenterProtocol?  { get set }
    func getCities() -> [City]
}

//MARK: View -
protocol AddCityViewProtocol: class {

  var presenter: AddCityPresenterProtocol?  { get set }
    func setCities(cities: [City])
}
