//
//  WeatherDetailRouter.swift
//  RiaWeather2
//
//  Created George Kyrylenko on 9/3/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherDetailRouter: WeatherDetailWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(view: WeatherDetailViewController) {
        let interactor = WeatherDetailInteractor()
        let router = WeatherDetailRouter()
        let presenter = WeatherDetailPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
    }
}
