//
//  WeatherDetailProtocols.swift
//  RiaWeather2
//
//  Created George Kyrylenko on 9/3/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import RxSwift

//MARK: Wireframe -
protocol WeatherDetailWireframeProtocol: class {

}
//MARK: Presenter -
protocol WeatherDetailPresenterProtocol: class {
    
    func getWeather(id: String)
}

//MARK: Interactor -
protocol WeatherDetailInteractorProtocol: class {

  var presenter: WeatherDetailPresenterProtocol?  { get set }
    func getWeather(id: String) -> Observable<WeatherData>
}

//MARK: View -
protocol WeatherDetailViewProtocol: class {
  var presenter: WeatherDetailPresenterProtocol?  { get set }
    func setWeather(weather: WeatherData)
}
