//
//  WeatherDetailInteractor.swift
//  RiaWeather2
//
//  Created George Kyrylenko on 9/3/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import RxSwift

class WeatherDetailInteractor: WeatherDetailInteractorProtocol {
    weak var presenter: WeatherDetailPresenterProtocol?
    
    func getWeather(id: String) -> Observable<WeatherData> {
        return DailyWeather.getDailyWeather(city: id)
    }
}
