//
//  WeatherDetailPresenter.swift
//  RiaWeather2
//
//  Created George Kyrylenko on 9/3/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherDetailPresenter: WeatherDetailPresenterProtocol {

    weak private var view: WeatherDetailViewProtocol?
    var interactor: WeatherDetailInteractorProtocol?
    private let router: WeatherDetailWireframeProtocol

    init(interface: WeatherDetailViewProtocol, interactor: WeatherDetailInteractorProtocol?, router: WeatherDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getWeather(id: String) {
        self.interactor?.getWeather(id: id).subscribe(onNext: { (weather) in
            self.view?.setWeather(weather: weather)
        }, onError: { (error) in
            print(error.localizedDescription)
        }, onCompleted: nil, onDisposed: nil)
    }

}
