//
//  WeatherRouter.swift
//  RiaWeather2
//
//  Created George Kyrylenko on 9/1/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherRouter: WeatherWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(view: WeatherViewController) {
        // Change to get view from storyboard if not using progammatic UI
        let interactor = WeatherInteractor()
        let router = WeatherRouter()
        let presenter = WeatherPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
    }
}
