//
//  WeatherPresenter.swift
//  RiaWeather2
//
//  Created George Kyrylenko on 9/1/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherPresenter: WeatherPresenterProtocol {

    

    weak private var view: WeatherViewProtocol?
    var interactor: WeatherInteractorProtocol?
    private let router: WeatherWireframeProtocol

    init(interface: WeatherViewProtocol, interactor: WeatherInteractorProtocol?, router: WeatherWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getWeather(){
        self.interactor?.getWeather().subscribe(onNext: { (weather) in
            self.view?.setWeather(weather: weather)
        }, onError: nil, onCompleted: nil, onDisposed: nil)
    }
}
