//
//  WeatherProtocols.swift
//  RiaWeather2
//
//  Created George Kyrylenko on 9/1/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import RxSwift

//MARK: Wireframe -
protocol WeatherWireframeProtocol: class {

}
//MARK: Presenter -
protocol WeatherPresenterProtocol: class {
    func getWeather()
}

//MARK: Interactor -
protocol WeatherInteractorProtocol: class {

  var presenter: WeatherPresenterProtocol?  { get set }
    
    func getWeather() -> Observable<WeatherData>
}

//MARK: View -
protocol WeatherViewProtocol: class {

  var presenter: WeatherPresenterProtocol?  { get set }
    func setWeather(weather: WeatherData)
}
